---
- name: generate user with random hashed password, store passwords in local files named 'password-(first-name) playbook'
  hosts: all
  user: lukerenwick
  vars_files:
    - users.yml
  tasks:
    - name: User task
      user:
        name: "{{ item.name }}"
        password: "{{ lookup('password', 'Password-' + item.first + ' length=6') | password_hash('sha512') }}"
        comment: "{{ item.first + ' ' + item.middle + ' ' + item.last }}"
        state: present
        uid: "{{ item.uid }}"
        loop: "{{ users }}"
